{% set data = load_setup_py_data() %}

package:
  name: datefinder
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pytz
    - regex>=2017.02.08
    - python-dateutil>=2.4.2

  run:
    - python
    - pytz
    - regex>=2017.02.08
    - python-dateutil>=2.4.2

test:
  imports:
    - datefinder

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
